CREATE PROC FI_SP_IncBeneficiario
	@CPF		   VARCHAR (11),
    @NOME          VARCHAR (50),
	@IDCLIENTE     BIGINT
AS
BEGIN

	IF EXISTS (SELECT 1 FROM BENEFICIARIOS WHERE CPF = @CPF)
		BEGIN
			RAISERROR('CPF está sendo utilizado, tente novamente!', 16, 1);
			RETURN;
		END

	INSERT INTO BENEFICIARIOS (CPF, NOME, IDCLIENTE) 
	VALUES (@CPF, @NOME, @IDCLIENTE)

	SELECT SCOPE_IDENTITY()
END