CREATE PROC FI_SP_IncClienteV3
    @NOME          VARCHAR (50) ,
    @SOBRENOME     VARCHAR (255),
    @NACIONALIDADE VARCHAR (50) ,
    @CEP           VARCHAR (9)  ,
    @ESTADO        VARCHAR (2)  ,
    @CIDADE        VARCHAR (50) ,
    @LOGRADOURO    VARCHAR (500),
    @EMAIL         VARCHAR (2079),
    @TELEFONE      VARCHAR (15),
	@CPF		   VARCHAR (11)
AS
BEGIN

	IF EXISTS (SELECT 1 FROM CLIENTES WHERE CPF = @CPF)
		BEGIN
			RAISERROR('CPF está sendo utilizado, tente novamente!', 16, 1);
			RETURN;
		END


	INSERT INTO CLIENTES (NOME, SOBRENOME, NACIONALIDADE, CEP, ESTADO, CIDADE, LOGRADOURO, EMAIL, TELEFONE, CPF) 
	VALUES (@NOME, @SOBRENOME,@NACIONALIDADE,@CEP,@ESTADO,@CIDADE,@LOGRADOURO,@EMAIL,@TELEFONE,@CPF)

	SELECT SCOPE_IDENTITY()
END